import Santa_Trinita from './pictures/lamps/Santa_Trinita.png';
import Elven_Blossom from './pictures/lamps/Elven_Blossom.png'

export const lampsInitialState = {
  lamp_01: {
    image: Santa_Trinita,
    product: 'Лампа настольная',
    name: 'Santa Trinita',
    article: 'GNM001',
    color: 'Лаванда',
    description: 'Функциональная дизайнерская лампа для создания максимально комфортного освещения',
    designer: 'Benjamin Moor',
    size: {
      height: '60см',
    },
    price: 150000,
  },
  lamp_02: {
    image: Elven_Blossom,
    product: 'Люстра',
    name: 'Elven Blossom',
    article: 'GNM002',
    color: 'Абрикос',
    description: 'Лампа в форме цветка с волшебным светом и переливами',
    designer: 'Ayla Silverleaf',
    size: {
      height: '60см',
    },
    price: 150000,
  },
  lamp_03: {
    image: null,
    product: 'Лампа настольная',
    name: 'Moonlit Branch',
    article: 'GNM003',
    color: 'Зеленый',
    description: 'Лампа, напоминающая изогнутую ветвь дерева с лунным светом',
    designer: 'Thalion Elensar',
    size: {
      height: '60см',
    },
    price: 150000,
  },
  lamp_04: {
    image: null,
    product: 'Лампа настольная',
    name: 'Starfall',
    article: 'GNM004',
    color: 'розовый',
    description: 'Кристальная лампа в виде падающей звезды, дарящая звёздный свет',
    designer: 'Eldrin Lightweaver',
    size: {
      height: '60см',
    },
    price: 150000,
  },
  lamp_05: {
    image: null,
    product: 'Лампа настольная',
    name: 'Forest Whisper',
    article: 'GNM005',
    color: 'голубой',
    description: 'Лампа в виде стебля с каплями светящейся росы, напоминающая лес',
    designer: 'Lirael Windwalker',
    size: {
      height: '60см',
    },
    price: 150000,
  },
  lamp_06: {
    image: null,
    product: 'Лампа настольная',
    name: 'Glade Flame',
    article: 'GNM006',
    color: 'лазурный',
    description: 'Лампа в виде огня в стеклянной сфере, напоминающая светлячков',
    designer: 'Finarfin Starbreeze',
    size: {
      height: '60см',
    },
    price: 150000,
  },
  lamp_07: {
    image: null,
    product: 'Лампа настольная',
    name: 'Elven Ivy',
    article: 'GNM007',
    color: 'розовый',
    description: 'Лампа с металлическими ветвями плюща, создающая магическое сияние',
    designer: 'Nimrodel Leafsong',
    size: {
      height: '60см',
    },
    price: 150000,
  },
  lamp_08: {
    image: null,
    product: 'Лампа настольная',
    name: 'Sylvan Mirror',
    article: 'GNM008',
    color: 'кедровый',
    description: 'Лампа-зеркало с орнаментом ветвей и игрой света и тени',
    designer: 'Elysia Moonshadow',
    size: {
      height: '60см',
    },
    price: 150000,
  },
  lamp_09: {
    image: null,
    product: 'Лампа настольная',
    name: 'Glimmering Grove',
    article: 'GNM009',
    color: 'абрикосовый',
    description: 'Лампа-дерево, украшенное светящимися кристаллами из эльфийских легенд',
    designer: 'Caelith Brightblade',
    size: {
      height: '60см',
    },
    price: 150000,
  },
  lamp_10: {
    image: null,
    product: 'Лампа настольная',
    name: 'Twilight Lotus',
    article: 'GNM010',
    color: 'лиловый',
    description: 'Лампа-лотос с мягким светом, символизирующая гармонию и спокойствие',
    designer: 'Elowen Starflower',
    size: {
      height: '60см',
    },
    price: 150000,
  },
}